version: "3.4"

services:
  shop_db:
    container_name: shop_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ShopDB
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
